### ISSUE TITLE
Feature request: Able to select choice in a dropdown menu

### ISSUE THREAD

**Issue by sirrobin11** [robrobbins/specford#17]
![image](https://cloud.githubusercontent.com/assets/11840909/9012849/f485a730-376c-11e5-84d2-41efbfddb20d.png)

Like the menu above, we'll need a way to select options in a dropdown.  It exists in a few places on PlanWeb as well.  The console reads the following way for it:

![image](https://cloud.githubusercontent.com/assets/11840909/9012885/29fa35fc-376d-11e5-96ef-4c0877dd0d2c.png)

**Comment by robrobbins** [comment]
done as of latest commit
